var x = 500;
var y = 25;
var equals = x == y;
var notequals = x !== y;
var gt = x > y;
var lt = x < y;
var gtequals = x >= y;
var ltequals = x <= y;
console.log(equals);
console.log(notequals);
console.log(gt);
console.log(lt);
console.log(gtequals);
console.log(ltequals);
